//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterpolEntities : DbContext
    {
        private static MasterpolEntities _context;
        public MasterpolEntities()
            : base("name=MasterpolEntities")
        {
        }
        public static MasterpolEntities GetContext()
        {
            if(_context == null)
            {
                _context = new MasterpolEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<Material_type_import> Material_type_import { get; set; }
        public virtual DbSet<Partner_products_import> Partner_products_import { get; set; }
        public virtual DbSet<Partners_import> Partners_import { get; set; }
        public virtual DbSet<Partners_Name2> Partners_Name2 { get; set; }
        public virtual DbSet<Partners_Names> Partners_Names { get; set; }
        public virtual DbSet<Partners_Types> Partners_Types { get; set; }
        public virtual DbSet<Product_type_import> Product_type_import { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Products_import> Products_import { get; set; }
        public virtual DbSet<Products_import_name> Products_import_name { get; set; }
        public virtual DbSet<Products_import_type> Products_import_type { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
