//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners_import
    {
        public int id { get; set; }
        public Nullable<int> Partners_Type { get; set; }
        public Nullable<int> Partners_Name { get; set; }
        public Nullable<int> Director { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Adress { get; set; }
        public Nullable<int> INN { get; set; }
        public Nullable<int> Reiting { get; set; }
    
        public virtual Adress Adress1 { get; set; }
        public virtual Directors Directors { get; set; }
        public virtual Partners_Name2 Partners_Name2 { get; set; }
        public virtual Partners_Types Partners_Types { get; set; }
    }
}
