//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products_import
    {
        public int id { get; set; }
        public Nullable<int> Products { get; set; }
        public Nullable<int> Partners_name { get; set; }
        public Nullable<int> Count_Products { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Partners_Names Partners_Names { get; set; }
        public virtual Products Products1 { get; set; }
    }
}
